apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-templates
  description: A collection of all Backstage example templates
spec:
  type: github
  targets:
    - https://github.com/brexhq/backstage/blob/master/config/templates/golang-template.yaml
    - https://github.com/brexhq/backstage/blob/master/config/templates/kotlin-template.yaml
    - https://github.com/brexhq/backstage/blob/master/config/templates/elixir-template.yaml